version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: 964736750795.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: AKIA6BHWKSTFYUZ23BQK  # can specify string literal values
          aws_secret_access_key: $nVAGzX8GdQ9AYt+h9mShm15p7DrjQ5mjxW8qCe/N  # or project UI envar reference

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://demo-ci-cd-article/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master